language: node_js
node_js: node
addons:
  chrome: stable
script:
- npm run lint
- |
  if [ $TRAVIS_PULL_REQUEST != false ] && [ $TRAVIS_SECURE_ENV_VARS == true ]; then
    echo "Pull request with secure environment variables, running Sauce tests...";
    npm run test:polymer:sauce || travis_terminate 1;
  else
    echo "Not a pull request and/or no secure environment variables, running headless tests...";
    npm run test:polymer:local || travis_terminate 1;
  fi
after_success:
- frauci-update-version -d=skip && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  skip_cleanup: true
  api_key:
    # 5613......9102
    secure: JW4Wc3YM7fHxmaSDa6gn3x2my/g41RHmlWkBjkY+YGZV+LQOs+jE0KXkNvfGPhpVqH8HsGzzcA78BU/4H/Jlel4wfzZuz6TGfJnxDb7swLlkC0DR5XH75qScCEBq2APpYLqSaVHXah3bw02cfZNMuQul96txvJcChpBk+hYc86RKjIQXx17mZqtNhsv4yHmDAUo8FhduSJN0Z69NIKwBJAoITawo0pyFmbLrxM4rV1CzOCB2PIDpc4yZGJ3rWmcMdQsvcflitvBNSp7oUIVksvRXdjA97LscLqUhI56pn5uBPr3IEBdSfNfOi+ZxVlMoa6tgCPfPJplFPPLcrdSHLcr79DHfMgblg4+ivmGV+T+KJVKzVpAlmsM8f6IgTEpyKGt/yTqqCu6b3LOvN1qiWyo3FYr7u84SEQOUxT4nP7OPG4aSiQOeyQyHdUtqzMgxAKK+vq7k9R9fIgsIUPYXACOJNO7dudfFZMYrFf0aQ1vcotWIK6QpbR4Prj9KhWDmleXZ2TkP7NLa5hOAVx3GBmzTwzqM1hwHyNXUNFjFXq8R8DsefI3mtltlha+Uyl38TalMGQpmWzfIk/LPLRLRYn32a4Cl3MgR0bm7kBUste90wtKlnJwIkJGfg2ib+6wxhFzw2AIU92kmqnKJAjO92mv5jdyclEy/g8Dg1W6l+/Q=
  on:
    repo: BrightspaceUILabs/page-load-progress
    tags: true
env:
  global:
  - OWNER_NAME=BrightspaceUILabs
  - REPO_NAME=page-load-progress
  - SAUCE_USERNAME: Gaudi1
  # SAUCE_ACCESS_KEY
  - secure: HFTanA1Y/msWeoSB9wZqjZBsqJFgE9IaSAFOAxlTN0txrqYr9g89cMR+wSEYIYjFY8a3bgqf1iJkAytY9bBsXSP2/cclo6w7r0DgDuF7NKxvMV++G+VAzzwNkYdfsNNzCv4mUy0Px/n/LQk42PSfC/bB+8OEVegoe2y6PvxgA+4wvLJKVjXeuWVfHj0g/TcIDD8M7gMywUGJzL5obUTHmq7gu/bI2JM6w6B5H8WBUGH3h344UQ359yHdla8n8axdQXPNiwYvXiMDHThTizjdiovtUAEd5erwOWOaXQoIplneaKB6ojrPlPoitQIG8wfhDP0G6hLtzq73OT09Z/zoi8ly4GtQsLaSFKe4V/Db+Wvpv9IOoZekIrXmac1lmf4S7vycqUbHfojT/OOc/1hpUublwN10q5at7pn/b4lw2X/6jS3YDPvgaTPac98F4oMW74rG4lEXsrhRkq3gI5/Tb7FvW9oLsw07y+xHFq7cGxDBbj5sIHdROXTG4NT93ZIKl49Oyc0/9HAGI5xjynhTMFWWn6TRBYnaOFFdgxTVGxUUl3M+ZgWp1ZM7kHqLfge+iakLyCoua/gKGARxnq+6/oDnzKDCvEsCabgHAhz5RAMR7EWV61R0siREkWCmwjVdOBOnxGS8gbdQPqaj3eaajd5BWRFIiXDguKmHCHaWwlE=
  # GITHUB_RELEASE_TOKEN
  - secure: HQsi4sQn2PFXk0naFIV5JLdrdrAJ8mhgHy8hR0BFcQ/gjCVpq4B5bDsC069yU8nMoIsEsHWSfd6P5sdZ6I33nPNCc5CqPMgl3K7rCqdVEIw1gdtAaGkdZYMcRhh0x3iEXHeTb1j6t57V9m5Ovu2RVVqIwNkKpCIQvJA7sKD+IF4EFdBhkhS3bKoRcsM9cuEMae9xI5TeJM+IWM61FU0OCHvIHWFeHDQg16k0MxzWpnbwdgn8k0bwbA7jAa+hfguyljU6oUv8+QUTpDnT7rR7QiTFkU48xl3YiCJshNNtR4V2OmYR+5gCL3JGG6B2xY2+j4rW+Ypq+W56EvioScVurJRamib9EAhXwRnlUIBn42tDRcbnOkofLn/bgeYLqR6Ox1I3EX+HVcPwqND6trgYc7nUuAdhT0D1pQymGHKJzTwfOR5sreIvXV1K9Q1oVx+txFZLHjx74NBRlunqXAsoG4hj/Agw8eesjitGGmsxstBiEgTTdTtrV6718Cvd0gwuT54zmXLEA0GUf+Sz7UPLSpXaO6ITYsjLLuDlh38p04xH/blOt5vlh5nBKJJ3J1Hm9JcRhtEVlm+dWaBn7Yl2nveJlpV6GRqg3xm/i+zHQF8UT3lVKGbR40wdlZsmm/PrKElSs9mbDZvJdGUC4BEecnGQagOZf+fQqloaA7jkpM8=
